### PR TITLE
Updated styles.go with Additional Font & Text Style Properties

### PR DESCRIPTION
**Pull request by Emm-dev0**
added support for additional font and text style properties.

----
#38

### CODE REVIEW

**Review by chasefleming — CHANGES_REQUESTED** [review]
Hi @Emm-dev0 , please uppercase the first letter of each of the constants so it matches the rest of the file and they are exported. Thanks!

**Comment by Emm-dev0** [comment]
I have updated it

**Review by chasefleming — APPROVED** [review]
Looks good, thanks!

**Comment by Emm-dev0** [comment]
You are welcome, hoping to contribute to many more of your projects as possible. Thank you

**Comment by Emm-dev0** [comment]
I am grateful 🙂💯

**Pull request merged**
