### PR TITLE
Add hx-ws

### PR DESCRIPTION
**Pull request by chasefleming**

### CODE REVIEW

**Comment by dreth** [comment]
Hey Chase, I didn't add hx-ws in my PR because of this:

image

But since you already added it, maybe you can also include hx-sse too, which is in the same condition (moved to an extension)

**Comment by chasefleming** [comment]
@dreth can you link that? Can't find it. From another page, I see that it only moves to an extension in v2, correct? I don't see an issue with adding support for anything in v1 as well. Is there anything else you thing would be beneficial as well that is currently missing?

**Comment by gedw99** [comment]
https://htmx.org/extensions/server-sent-events/

import:  https://unpkg.com/htmx.org/dist/ext/sse.js

---

https://htmx.org/extensions/web-sockets/

import: https://unpkg.com/htmx.org/dist/ext/ws.js

**Comment by chasefleming** [comment]
Thanks @gedw99 ! Do you all think we should add `sse-connect`, `sse-swap`, and `ws-connect` as well?

**Comment by dreth** [comment]
What @gedw99 linked is more complete, but the screenshot i attached is from the end of this table: https://htmx.org/reference/#attributes-additional

**Comment by chasefleming** [comment]
Sure, that would be awesome. Thanks @dreth !

**Pull request merged**
